# Hexo 配置文件
## 文档: https://hexo.io/docs/configuration.html
## 开源地址: https://github.com/hexojs/hexo/
## 汉化：该配置文件由酷友@https://www.coolapk.com/u/827277?from=qr 汉化

# 网站
title: 欢迎访问俺的博客		#网站标题
subtitle: ''			#网站小标题
description: '熊孩子的博客'	#网站描述
keywords: 博客 个人博客 hexo	#关键字
author: 某不知名的熊孩子	#网站作者
language: en			#语言
timezone: 'Asia/Shanghai'	#时区

# 网站地址
## 如果您的网站位于子目录中，则将url设置为“ http://yoursite.com/child”，将根目录设置为'/child/'
url: https://3207754367.github.io	#网站地址
root: 3207754367.github.io 		#网站根目录
permalink: :year/:month/:day/:urlname/	#永久链接	
permalink_defaults:			#永久链接默认值
pretty_urls:
  trailing_index: true			#设置是否可从永久链接中删除尾随的'index.html'
  trailing_html: true			#设置是否可从永久链接中删除尾随的'.html'

# 目录
source_dir: source 	  #资源目录，文件夹内的文件将上传至github中
public_dir: public	  #公共目录，用来存放生产的静态文件
tag_dir: tags      	  #标签目录，默认的tags 实际存放路径为source/tags
archive_dir: archives     #档案目录，默认是archives
category_dir: categories  #类别目录，默认是categories 实际存放路径为source/categories
code_dir: downloads/code  #代码目录，默认是downloads/code 
i18n_dir: :lang		  #国际化目录，默认与language一致
# 指定不需要渲染的文件或文件夹，以“,”分开
skip_render: [README.md]

# 新帖子配置
new_post_name: :title.md # 新帖子的文件名
default_layout: post	# 默认布局模板
titlecase: false 	# 设置是否可将标题转换为标题形式
external_link:		
  enable: false 	# 设置是否在新标签页中打开外部链接
  field: site 		# 应用于整个网站
  exclude: ''		#
filename_case: 0	#文件名大小写
render_drafts: false    #设置是否渲染草稿
post_asset_folder: false #设置是否使用资源文件夹，Hexo将会创建新文章时自动创建一个文件夹
relative_link: true	#设置是否把链接改为与根目录的相对位置
future: true		#设置是否显示未来的文章
highlight:		
  enable: true		#设置是否启用代码高亮
  line_number: true	#设置是否显示行号
  auto_detect: true	#设置是否自动检测语言
  tab_replace: ''	#替换tab为''
  wrap: true		#在显示边界处换行显示
  hljs: true		#设置是否使用highlightjs主题高亮

# 主页设置
# path: 您的博客索引页面的根路径 （默认=''）
# per_page：每页显示的帖子 （0=禁用分页）
# order_by：按发布顺序 （默认按日期降序排列）
index_generator:	#索引生成器
  path: ''
  per_page: 10
  order_by: -date

# 分类和标签
default_category: uncategorized		#设置默认分类方式，默认为未分类
category_map:				#设置分类别名
tag_map:				#设置标签别名

#  元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo 使用Moment.js解析和显示日期
##您可以参照下面的网站自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## 除非在post 中设置，否则使用帖子的日期作为更新日期
use_date_for_updated: false	#设置是否启用更新的日期

# Pagination 分页
## 将per_page设置为0以禁用分页
per_page: 10
pagination_dir: page

# 包含/排除文件
## include:/exclude: 选项仅适用于“source/”文件夹
include:
exclude:
ignore:

# Extensions拓展插件配置
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next

# 自定义站点内容搜索
# 需要先安装插件：
# npm install hexo-generator-search --save
search:
  path: search.xml
  # 如只想索引文章，可设置为post
  field: all

# 配置RSS
feed: 
  #feed 类型 (atom/rss2)
  type: atom   
  #rss 路径
  path: atom.xml  
  #在 rss 中最多生成的文章数(0显示所有)
  limit: 0

jsonContent:
  meta: false
  pages: false
  posts:
  title: true
  date: true
  path: true
  text: false
  raw: false
  content: false
  slug: false
  updated: false
  comments: false
  link: false
  permalink: false
  excerpt: false
  categories: false
  tags: true

# 部署方式
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/3207754367/3207754367.github.io.git
	#部署到github
  #coding: git@git.coding.net/
	# 部署到coding.net。取消注释可同时部署
  branch: master
